import { ICharBackground } from '../models/ICharBackground';

export const charBackgrounds: ICharBackground[] = [
  {
    backgroundId: 'cbg01',
    name: 'Acolyte',
    desc: `You have spent your life in service to a temple, learning sacred rites and providing sacrifices to the god or gods you worship. Serving the gods and discovering their sacred works will guide you to greatness.`,
    imgSrc: './icons/charBackgrounds/Acolyte_Icon.png',
    skillProficienciesGiven: ['ski11', 'ski09'],
  },
  {
    backgroundId: 'cbg02',
    name: 'Charlatan',
    desc: `You're an expert in manipulation, prone to exaggeration and more than happy to profit from it. Bending the truth and turning allies against each other will lead to greater success down the road.`,
    imgSrc: './icons/charBackgrounds/Charlatan_Icon.png',
    skillProficienciesGiven: ['ski15', 'ski03'],
  },
  {
    backgroundId: 'cbg03',
    name: 'Criminal',
    desc: `You're an expert in manipulation, prone to exaggeration and more than happy to profit from it. Bending the truth and turning allies against each other will lead to greater success down the road.`,
    imgSrc: './icons/charBackgrounds/Criminal_Icon.png',
    skillProficienciesGiven: ['ski15', 'ski04'],
  },
  {
    backgroundId: 'cbg04',
    name: 'Entertainer',
    desc: `You live to sway and subvert your audience, engaging common crowds and high society alike. Preserving art and bringing joy to the hapless and downtrodden heightens your charismatic aura.`,
    imgSrc: './icons/charBackgrounds/Entertainer_Icon.png',
    skillProficienciesGiven: ['ski02', 'ski17'],
  },
  {
    backgroundId: 'cbg05',
    name: 'Folk Hero',
    desc: `You live to sway and subvert your audience, engaging common crowds and high society alike. Preserving art and bringing joy to the hapless and downtrodden heightens your charismatic aura.`,
    imgSrc: './icons/charBackgrounds/Folk_Hero_Icon.png',
    skillProficienciesGiven: ['ski10', 'ski14'],
  },
  {
    backgroundId: 'cbg06',
    name: 'Guild Artisan',
    desc: `Your skill in a particular craft has earned you membership in a mercantile guild, offering privileges and protection while engaging in your art. Repairing and discovering rare crafts will bring new inspiration.`,
    imgSrc: './icons/charBackgrounds/Guild_Artisan_Icon.png',
    skillProficienciesGiven: ['ski11', 'ski18'],
  },
  {
    backgroundId: 'cbg07',
    name: 'Haunted One (Dark Urge)',
    desc: `A wicked moment, person, or thing that cannot be slain by sword or spell haunts your mind and flickers in your peripheral vision. You carry it wherever your adventure takes you - or perhaps it carries you.`,
    imgSrc: './icons/charBackgrounds/Haunted_One_Icon.png',
    skillProficienciesGiven: ['ski12', 'ski16'],
  },
  {
    backgroundId: 'cbg08',
    name: 'Noble',
    desc: `You were raised in a family among the social elite, accustomed to power and privilege. Accumulating renown, power, and loyalty will raise your status.`,
    imgSrc: './icons/charBackgrounds/Noble_Icon.png',
    skillProficienciesGiven: ['ski06', 'ski18'],
  },
  {
    backgroundId: 'cbg09',
    name: 'Outlander',
    desc: `You grew up in the wilds, learning to survive far from the comforts of civilisation. Surviving unusual hazards of the wild will enhance your prowess and understanding.`,
    imgSrc: './icons/charBackgrounds/Outlander_Icon.png',
    skillProficienciesGiven: ['ski01', 'ski14'],
  },
  {
    backgroundId: 'cbg10',
    name: 'Sage',
    desc: `You are curious and well-read, with an unending thirst for knowledge. Learning about rare lore of the world will inspire you to put this knowledge to greater purpose.`,
    imgSrc: './icons/charBackgrounds/Sage_Icon.png',
    skillProficienciesGiven: ['ski05', 'ski06'],
  },
  {
    backgroundId: 'cbg11',
    name: 'Soldier',
    desc: `You are trained in battlefield tactics and combat, having served in a militia, mercenary company, or officer corps. Show smart tactics and bravery on the battlefield to enhance your prowess.`,
    imgSrc: './icons/charBackgrounds/Soldier_Icon.png',
    skillProficienciesGiven: ['ski01', 'ski16'],
  },
  {
    backgroundId: 'cbg12',
    name: 'Urchin',
    desc: `After surviving a poor and bleak childhood, you know how to make the most out of very little. Using your street smarts bolsters your spirit for the journey ahead.`,
    imgSrc: './icons/charBackgrounds/Urchin_Icon.png',
    skillProficienciesGiven: ['ski03', 'ski04'],
  },
];
