import {
  EquipmentTypes,
  IEquipmentProficiencies,
} from '../models/IEquipmentProficiencies';

export enum EEquipment {
  LightArmor = 'eqp01',
  MediumArmor = 'eqp02',
  HeavyArmor = 'eqp03',
  Shields = 'eqp04',
  SimpleW = 'eqp05',
  MartialW = 'eqp06',
  Clubs = 'eqp07',
  Daggers = 'eqp08',
  Handaxes = 'eqp09',
  Javelins = 'eqp10',
  LightHammers = 'eqp11',
  Maces = 'eqp12',
  Sickles = 'eqp13',
  Quarterstaves = 'eqp14',
  Spears = 'eqp15',
  Greatclubs = 'eqp16',
  LightCrossbows = 'eqp17',
  Shortbows = 'eqp18',
  Flails = 'eqp19',
  Morningstars = 'eqp20',
  Rapiers = 'eqp21',
  Scimitars = 'eqp22',
  Shortswords = 'eqp23',
  WarPicks = 'eqp24',
  Battleaxes = 'eqp25',
  Longswords = 'eqp26',
  Tridents = 'eqp27',
  Warhammers = 'eqp28',
  Glaives = 'eqp29',
  Greataxes = 'eqp30',
  Greatswords = 'eqp31',
  Halberds = 'eqp32',
  Mauls = 'eqp33',
  Pikes = 'eqp34',
  HandCrossbows = 'eqp35',
  HeavyCrossbows = 'eqp36',
  Longbows = 'eqp37',
}

export const equipmentProficiencies: IEquipmentProficiencies[] = [
  {
    equipmentId: 'eqp01',
    name: 'Light Armor',
    equipmentType: EquipmentTypes.Armor,
  },
  {
    equipmentId: 'eqp02',
    name: 'Medium Armor',
    equipmentType: EquipmentTypes.Armor,
  },
  {
    equipmentId: 'eqp03',
    name: 'Heavy Armor',
    equipmentType: EquipmentTypes.Armor,
  },
  {
    equipmentId: 'eqp04',
    name: 'Shields',
    equipmentType: EquipmentTypes.Armor,
  },
  {
    equipmentId: 'eqp05',
    name: 'Simple Weapons',
    equipmentType: EquipmentTypes.SimpleW,
  },
  {
    equipmentId: 'eqp06',
    name: 'Martial Weapons',
    equipmentType: EquipmentTypes.MartialW,
  },
  {
    equipmentId: 'eqp07',
    name: 'Clubs',
    equipmentType: EquipmentTypes.SimpleW,
  },
  {
    equipmentId: 'eqp08',
    name: 'Daggers',
    equipmentType: EquipmentTypes.SimpleW,
  },
  {
    equipmentId: 'eqp09',
    name: 'Handaxes',
    equipmentType: EquipmentTypes.SimpleW,
  },
  {
    equipmentId: 'eqp10',
    name: 'Javelins',
    equipmentType: EquipmentTypes.SimpleW,
  },
  {
    equipmentId: 'eqp11',
    name: 'Light Hammers',
    equipmentType: EquipmentTypes.SimpleW,
  },
  {
    equipmentId: 'eqp12',
    name: 'Maces',
    equipmentType: EquipmentTypes.SimpleW,
  },
  {
    equipmentId: 'eqp13',
    name: 'Sickles',
    equipmentType: EquipmentTypes.SimpleW,
  },
  {
    equipmentId: 'eqp14',
    name: 'Quarterstaves',
    equipmentType: EquipmentTypes.SimpleW,
  },
  {
    equipmentId: 'eqp15',
    name: 'Spears',
    equipmentType: EquipmentTypes.SimpleW,
  },
  {
    equipmentId: 'eqp16',
    name: 'Greatclubs',
    equipmentType: EquipmentTypes.SimpleW,
  },
  {
    equipmentId: 'eqp17',
    name: 'Light Crossbows',
    equipmentType: EquipmentTypes.SimpleW,
  },
  {
    equipmentId: 'eqp18',
    name: 'Shortbows',
    equipmentType: EquipmentTypes.SimpleW,
  },
  {
    equipmentId: 'eqp19',
    name: 'Flails',
    equipmentType: EquipmentTypes.MartialW,
  },
  {
    equipmentId: 'eqp20',
    name: 'Morningstars',
    equipmentType: EquipmentTypes.MartialW,
  },
  {
    equipmentId: 'eqp21',
    name: 'Rapiers',
    equipmentType: EquipmentTypes.MartialW,
  },
  {
    equipmentId: 'eqp22',
    name: 'Scimitars',
    equipmentType: EquipmentTypes.MartialW,
  },
  {
    equipmentId: 'eqp23',
    name: 'Shortswords',
    equipmentType: EquipmentTypes.MartialW,
  },
  {
    equipmentId: 'eqp24',
    name: 'War Picks',
    equipmentType: EquipmentTypes.MartialW,
  },
  {
    equipmentId: 'eqp25',
    name: 'Battleaxes',
    equipmentType: EquipmentTypes.MartialW,
  },
  {
    equipmentId: 'eqp26',
    name: 'Longswords',
    equipmentType: EquipmentTypes.MartialW,
  },
  {
    equipmentId: 'eqp27',
    name: 'Tridents',
    equipmentType: EquipmentTypes.MartialW,
  },
  {
    equipmentId: 'eqp28',
    name: 'Warhammers',
    equipmentType: EquipmentTypes.MartialW,
  },
  {
    equipmentId: 'eqp29',
    name: 'Glaives',
    equipmentType: EquipmentTypes.MartialW,
  },
  {
    equipmentId: 'eqp30',
    name: 'Greataxes',
    equipmentType: EquipmentTypes.MartialW,
  },
  {
    equipmentId: 'eqp31',
    name: 'Greatswords',
    equipmentType: EquipmentTypes.MartialW,
  },
  {
    equipmentId: 'eqp32',
    name: 'Halberds',
    equipmentType: EquipmentTypes.MartialW,
  },
  {
    equipmentId: 'eqp33',
    name: 'Mauls',
    equipmentType: EquipmentTypes.MartialW,
  },
  {
    equipmentId: 'eqp34',
    name: 'Pikes',
    equipmentType: EquipmentTypes.MartialW,
  },
  {
    equipmentId: 'eqp35',
    name: 'Hand Crossbows',
    equipmentType: EquipmentTypes.MartialW,
  },
  {
    equipmentId: 'eqp36',
    name: 'Heavy Crossbows',
    equipmentType: EquipmentTypes.MartialW,
  },
  {
    equipmentId: 'eqp37',
    name: 'Longbows',
    equipmentType: EquipmentTypes.MartialW,
  },
];
