import { ISubClass } from '../models/ISubClass';
import { EEquipment } from './dbEquipmentProficiencies';

export enum ESubClasses {
  Berserker = 'scl01',
  WildMagicBarb = 'scl02',
  Wildheart = 'scl03',
  Lore = 'scl04',
  Valour = 'scl05',
  Swords = 'scl06',
  Life = 'scl07',
  Light = 'scl08',
  Trickery = 'scl09',
  Knowledge = 'scl10',
  Nature = 'scl11',
  Tempest = 'scl12',
  War = 'scl13',
  Land = 'scl14',
  Spores = 'scl15',
  BattleMaster = 'scl16',
  EldritchKnight = 'scl17',
  Champion = 'scl18',
  FourElements = 'scl19',
  OpenHand = 'scl20',
  Shadow = 'scl21',
  Ancients = 'scl22',
  Devotion = 'scl23',
  Vengeance = 'scl24',
  Oathbreaker = 'scl25',
  Hunter = 'scl26',
  BeastMaster = 'scl27',
  GloomStalker = 'scl28',
  Thief = 'scl29',
  ArcaneTrickster = 'scl30',
  Assassin = 'scl31',
  WildMagicSorc = 'scl32',
  Draconic = 'scl33',
  StormSorcery = 'scl34',
  Fiend = 'scl35',
  GreatOldOne = 'scl36',
  Archfey = 'scl37',
  Abjuration = 'scl38',
  Evocation = 'scl39',
  Necromancy = 'scl40',
  Conjuration = 'scl41',
  Enchantment = 'scl42',
  Divination = 'scl43',
  Illusion = 'scl44',
  Transmutation = 'scl45',
  Moon = 'scl46',
}

export const subClasses: ISubClass[] = [
  {
    subClassId: 'scl01',
    name: 'Berserker',
    desc: 'Violence is both a means and an end. You follow a path of untrammelled fury, slick with blood, as you thrill in the chaos of battle, heedless of your own well-being.',
    imgUrl: './icons/subClasses/Barbarian_Berserker_Icon.png',
    specialSkills: [],
  },
  {
    subClassId: 'scl02',
    name: 'Wild Magic',
    desc: `The wild influence of magic has transformed you, suffusing you with an arcane power that churns within you, waiting to be released.`,
    imgUrl: './icons/subClasses/Barbarian_Wild_Magic_Icon.png',
    specialSkills: [],
  },
  {
    subClassId: 'scl03',
    name: 'Wildheart',
    desc: `Your attunement with nature and its beasts inspires your rage, empowering you with supernatural might.`,
    imgUrl: './icons/subClasses/Barbarian_Wildheart_Icon.png',
    specialSkills: [],
  },
  {
    subClassId: 'scl04',
    name: 'College of Lore',
    desc: `You pursue beauty and truth, collecting knowledge from scholarly tomes to peasants' tales, and use your gifts to hold both audiences and enemies spellbound.`,
    imgUrl: './icons/subClasses/Bard_Lore_Icon.png',
    skillProficiencySlots: 3,
    specialSkills: [],
  },
  {
    subClassId: 'scl05',
    name: 'College of Valour',
    desc: `You wander the land to witness and relate the deeds of the mighty, keeping alive the memory of heroes of the past and inspiring heroes of the future.`,
    imgUrl: './icons/subClasses/Bard_Valour_Icon.png',
    armorProficiencies: [EEquipment.MediumArmor, EEquipment.Shields],
    weaponProficiencies: [EEquipment.MartialW],
    specialSkills: [],
  },
  {
    subClassId: 'scl06',
    name: 'College of Swords',
    desc: `A highly trained and skilled warrior, you use your prowess with words and weapons to fight and entertain in equal measure.`,
    imgUrl: './icons/subClasses/Bard_Swords_Icon.png',
    armorProficiencies: [EEquipment.MediumArmor],
    weaponProficiencies: [EEquipment.Scimitars],
    specialSkills: [],
  },
  {
    subClassId: 'scl07',
    name: 'Life Domain',
    desc: `Tasked with the holy edict of preserving the body, mind, and soul, your god grants you a plethora of healing magics.`,
    imgUrl: './icons/subClasses/Cleric_Life_Icon.png',
    armorProficiencies: [EEquipment.HeavyArmor],
    specialSkills: [],
  },
  {
    subClassId: 'scl08',
    name: 'Light Domain',
    desc: `Gods of primordial flame bathe you in resplendent light, providing magics to dispel darkness and immolate enemies.`,
    imgUrl: './icons/subClasses/Cleric_Light_Icon.png',
    specialSkills: [],
  },
  {
    subClassId: 'scl09',
    name: 'Trickery Domain',
    desc: `You wield the unorthodox divine tools of deceit and illusion in worship of your chosen deity.`,
    imgUrl: './icons/subClasses/Cleric_Trickery_Icon.png',
    specialSkills: [],
  },
  {
    // add expertise to this one
    subClassId: 'scl10',
    name: 'Knowledge Domain',
    desc: `Adaptable and adroit in all manner of languages and skills, your mind is an intellectual cup brimming with exquisite knowing.`,
    imgUrl: './icons/subClasses/Cleric_Knowledge_Icon.png',
    specialSkills: [],
  },
  {
    // add proficiency to this one
    subClassId: 'scl11',
    name: 'Nature Domain',
    desc: `You embody the vast viridian power of the natural world, an avatar of the subtle divinity of fruitfall, avian migration, woodland silence, and the landslide's roaring fury.`,
    imgUrl: './icons/subClasses/Cleric_Nature_Icon.png',
    armorProficiencies: [EEquipment.HeavyArmor],
    specialSkills: [],
  },
  {
    subClassId: 'scl12',
    name: 'Tempest Domain',
    desc: `Your faith has made you the very thunder that quakes the black firmament, the lightning coursing through the veins of a terrible storm.`,
    imgUrl: './icons/subClasses/Cleric_Tempest_Icon.png',
    armorProficiencies: [EEquipment.HeavyArmor],
    weaponProficiencies: [EEquipment.MartialW],
    specialSkills: [],
  },
  {
    subClassId: 'scl13',
    name: 'War Domain',
    desc: `Fortified by holy zeal, you brandish an arsenal of sacramental savagery to use against those you deem unrighteous.`,
    imgUrl: './icons/subClasses/Cleric_War_Icon.png',
    armorProficiencies: [EEquipment.HeavyArmor],
    weaponProficiencies: [EEquipment.MartialW],
    specialSkills: [],
  },
  {
    subClassId: 'scl14',
    name: 'Circle of the Land',
    desc: `You channel the natural arcana flowing through the earth and creatures atop it to cast powerful druidic magic.`,
    imgUrl: './icons/subClasses/Druid_Land_Icon.png',
    specialSkills: [],
  },
  {
    subClassId: 'scl46',
    name: 'Circle of the Moon',
    desc: `Your form is mutable as the mercurial moon, letting you shift your form into massive beasts and even primal elementals.`,
    imgUrl: './icons/subClasses/Druid_Moon_Icon.png',
    specialSkills: [],
  },
  {
    subClassId: 'scl15',
    name: 'Circle of the Spores',
    desc: `Viewing death, necrosis, fungal growth, and sporulation as just another part of life, you can manipulate such spores to augment yourself and harm your foes.`,
    imgUrl: './icons/subClasses/Druid_Spores_Icon.png',
    specialSkills: [],
  },
  {
    subClassId: 'scl16',
    name: 'Battle Master',
    desc: `As a paragon of tactical superiority, you employ a wide array of combat manoeuvres to dominate every fight.`,
    imgUrl: './icons/subClasses/Fighter_Battle_Master_Icon.png',
    specialSkills: [],
  },
  {
    subClassId: 'scl17',
    name: 'Eldritch Knight',
    desc: `You are a warrior of spell and sword, weaving incantations that supplement your extensive martial expertise.`,
    imgUrl: './icons/subClasses/Fighter_Eldritch_Knight_Icon.png',
    specialSkills: [],
  },
  {
    subClassId: 'scl18',
    name: 'Champion',
    desc: `You approach the complex problems posed by combat with one distinctly effective solution - you hit those problems, really quite hard.`,
    imgUrl: './icons/subClasses/Fighter_Champion_Icon.png',
    specialSkills: [],
  },
  {
    subClassId: 'scl19',
    name: 'Way of the Four Elements',
    desc: `You focus your ki to bend the elements to your will, using them as an extension of your own body.`,
    imgUrl: './icons/subClasses/Monk_Four_Elements_Icon.png',
    specialSkills: [],
  },
  {
    subClassId: 'scl20',
    name: 'Way of the Open Hand',
    desc: `You specialise in unarmed combat, using your hands and your control of ki to heal or inflict grievous hurt.`,
    imgUrl: './icons/subClasses/Monk_Open_Hand_Icon.png',
    specialSkills: [],
  },
  {
    subClassId: 'scl21',
    name: 'Way of Shadow',
    desc: `You value the arts of stealth and subterfuge, bending the shadows to your will to strike without warning.`,
    imgUrl: './icons/subClasses/Monk_Shadow_Icon.png',
    specialSkills: [],
  },
  {
    subClassId: 'scl22',
    name: 'Oath of the Ancients',
    desc: `You fight on the side of light in the cosmic struggle against darkness to preserve the sanctity of life and the beauty of nature.`,
    imgUrl: './icons/subClasses/Paladin_Ancients_Icon.png',
    specialSkills: [],
  },
  {
    subClassId: 'scl23',
    name: 'Oath of Devotion',
    desc: `Following the ideal of the knight in shining armour, you act with honour and virtue to protect the weak and pursue the greater good.`,
    imgUrl: './icons/subClasses/Paladin_Devotion_Icon.png',
    specialSkills: [],
  },
  {
    subClassId: 'scl24',
    name: 'Oath of Vengeance',
    desc: `You have set aside even your own purity to right wrongs and deliver justice to those who have committed the most grievous sins.`,
    imgUrl: './icons/subClasses/Paladin_Vengeance_Icon.png',
    specialSkills: [],
  },
  {
    subClassId: 'scl25',
    name: 'Oathbreaker',
    desc: `You have broken your sacred Oath in pursuit of power and ambition. Only darkness remains to fuel you now.`,
    imgUrl: './icons/subClasses/Paladin_Oathbreaker_Icon.png',
    specialSkills: [],
  },
  {
    subClassId: 'scl26',
    name: 'Hunter',
    desc: `You seek the most dangerous prey in Faerûn, from ancient dragons to massive hordes of undead, and excel at slaying them all.`,
    imgUrl: './icons/subClasses/Ranger_Hunter_Icon.png',
    specialSkills: [],
  },
  {
    subClassId: 'scl27',
    name: 'Beast Master',
    desc: `You foster an intelligent bond with a powerful beast that can aid you in and out of combat.`,
    imgUrl: './icons/subClasses/Ranger_Beast_Master_Icon.png',
    specialSkills: [],
  },
  {
    subClassId: 'scl28',
    name: 'Gloom Stalker',
    desc: `Emerging like a horrible gift from the envelope of darkness and shadow, you ambush and put down your foes before they can even scream.`,
    imgUrl: './icons/subClasses/Ranger_Gloom_Stalker_Icon.png',
    specialSkills: [],
  },
  {
    subClassId: 'scl29',
    name: 'Thief',
    desc: `Your quick hands and mastery of the larcenous arts make stealing second nature - be it from a third floor window or a forgotten ruin.`,
    imgUrl: './icons/subClasses/Rogue_Thief_Icon.png',
    specialSkills: [],
  },
  {
    subClassId: 'scl30',
    name: 'Arcane Trickster',
    desc: `As quick with a spell as you are with a lockpick, your illusions and enchantments keep opponents on the back foot.`,
    imgUrl: './icons/subClasses/Rogue_Arcane_Trickster_Icon.png',
    specialSkills: [],
  },
  {
    subClassId: 'scl31',
    name: 'Assassin',
    desc: `You prefer to deal sublime punishment to a single foe at a time - not in a duel, mind, because a duel implies chivalry, and you're too busy getting the job done for honour.`,
    imgUrl: './icons/subClasses/Rogue_Assassin_Icon.png',
    specialSkills: [],
  },
  {
    subClassId: 'scl32',
    name: 'Wild Magic',
    desc: `Your powers come from ancient forces of chaos. They churn within you - waiting to burst free at any time.`,
    imgUrl: './icons/subClasses/Sorcerer_Wild_Magic_Icon.png',
    specialSkills: [],
  },
  {
    subClassId: 'scl33',
    name: 'Draconic Bloodline',
    desc: `Your veins carry draconic magic, the result of a powerful dragon ancestor.`,
    imgUrl: './icons/subClasses/Sorcerer_Draconic_Bloodline_Icon.png',
    specialSkills: [],
  },
  {
    subClassId: 'scl34',
    name: 'Storm Sorcery',
    desc: `Whether crackling with the energy of ancient deluges or pierced by gales and hurricanes, your lineage is a strange tapestry scrawled by a tempest.`,
    imgUrl: './icons/subClasses/Sorcerer_Storm_Sorcery_Icon.png',
    specialSkills: [],
  },
  {
    subClassId: 'scl35',
    name: 'The Fiend',
    desc: `You have pledged your soul to the Hells or Abyss in return for a deadly arsenal of fiendish arcana.`,
    imgUrl: './icons/subClasses/Warlock_Fiend_Icon.png',
    specialSkills: [],
  },
  {
    subClassId: 'scl36',
    name: 'The Great Old One',
    desc: `You pledged something unthinkable to an unspeakably ancient entity - which in return furnished you with powers of cerebral entropy and control.`,
    imgUrl: './icons/subClasses/Warlock_Great_Old_One_Icon.png',
    specialSkills: [],
  },
  {
    subClassId: 'scl37',
    name: 'The Archfey',
    desc: `Graced by a lady or lord of the fey, you are imbued with all the sumptuous and scary qualities of your patron's extraordinary realm.`,
    imgUrl: './icons/subClasses/Warlock_Archfey_Icon.png',
    specialSkills: [],
  },
  {
    subClassId: 'scl38',
    name: 'Abjuration School',
    desc: `You twist and harden the Weave into arcane wards to protect yourself and others.`,
    imgUrl: './icons/subClasses/Wizard_Abjuration_Icon.png',
    specialSkills: [],
  },
  {
    subClassId: 'scl39',
    name: 'Evocation School',
    desc: `You are known as an evoker - striding unharmed through the unfettered chaos you call.`,
    imgUrl: './icons/subClasses/Wizard_Evocation_Icon.png',
    specialSkills: [],
  },
  {
    subClassId: 'scl40',
    name: 'Necromancy School',
    desc: `You walk through the valley of the shadow of death, and make lots of friends there`,
    imgUrl: './icons/subClasses/Wizard_Necromancy_Icon.png',
    specialSkills: [],
  },
  {
    subClassId: 'scl41',
    name: 'Conjuration School',
    desc: `Compelled by shape and motion, your favoured arcane style involves summoning creatures and objects, as well as displacing them in space.`,
    imgUrl: './icons/subClasses/Wizard_Conjuration_Icon.png',
    specialSkills: [],
  },
  {
    subClassId: 'scl42',
    name: 'Enchantment School',
    desc: `Your magic influences, beguiles, and bends the will and conviction of those around you.`,
    imgUrl: './icons/subClasses/Wizard_Enchantment_Icon.png',
    specialSkills: [],
  },
  {
    subClassId: 'scl43',
    name: 'Divination School',
    desc: `You peer through time itself and can sculpt the future, like temporal clay, into a more favourable form.`,
    imgUrl: './icons/subClasses/Wizard_Divination_Icon.png',
    specialSkills: [],
  },
  {
    subClassId: 'scl44',
    name: 'Illusion School',
    desc: `You specialise in unravelling and restitching the fabric of reality to fool the unwary, the gullible, and the monstrous.`,
    imgUrl: './icons/subClasses/Wizard_Illusion_Icon.png',
    specialSkills: [],
  },
  {
    subClassId: 'scl45',
    name: 'Transmutation School',
    desc: `Your innate fascination with the structure of things has granted you an incredible power over crude matter and its manipulation.`,
    imgUrl: './icons/subClasses/Wizard_Transmutation_Icon.png',
    specialSkills: [],
  },
];
